imports:
- ../cmd/tpl_gen/yaml/settings.yaml
value_sets:
  go:
    package: roles
templates:
- template: ../cmd/tpl_gen/tpl/const_type.go.tpl
  out: roles.gen.go
  value_sets:
  - go
  - roles
  values:
    type_name: Role
    type_desc: role
