value_sets:
  # roles
  roles:
    consts:
    - name: Buyer
      value: buyer
    - name: Seller
      value: seller

  # networks
  networks:
    consts:
    - name: MainNet
      value: mainnet
    - name: TestNet
      value: testnet
    - name: SimNet
      value: simnet
    - name: RegressionNet
      value: regnet

  # types of cryptocurrencies
  crypto_types:
    consts:
    - name: UTXO
      value: utxo
    - name: StateBased
      value: state-based
    - name: ERC20Token
      value: erc20-token

  # cryptos
  cryptos:
    cryptos:
      BTC:
        name: bitcoin
        type: UTXO
        decimals: 8
      LTC:
        name: litecoin
        type: UTXO
        decimals: 8
      DOGE:
        name: dogecoin
        type: UTXO
        decimals: 8
      BCH:
        name: bitcoin-cash
        type: UTXO
        decimals: 8
      DCR:
        name: decred
        type: UTXO
        decimals: 8

  # crypto data
  ltc_data:
    name: litecoin
    short: LTC
    type: UTXO
    decimals: 8
  doge_data:
    name: dogecoin
    short: DOGE
    type: UTXO
    decimals: 8
  bch_data:
    name: bitcoin-cash
    short: BCH
    type: UTXO
    decimals: 8
  dcr_data:
    name: decred
    short: DCR
    type: UTXO
    decimals: 8
